### ISSUE TITLE
Compose file is invalid errors?

### ISSUE THREAD

**Issue by thepenguinthatwants** [norweeg/self-hosted-docker-server-templates#6]
Hi!

I tried to run your docker-compose.yml files that I found from self-hosted-docker-server-templates/add-ons/

Docker-compose version 1.24.1
Docker version 18.09.7-ce, build 2d0083d657

For example when I tried the grocy version and added my own values to .env file. 

When I ran docker-compose up

I get
```

ERROR: The Compose file is invalid because:
Service reverse-proxy has neither an image nor a build context specified. At least one must be provided.
```

What might also need to be changed? I am running these on my localhost

So I've defined this to my .env file.

`GROCY_DOMAIN=grocy.localhost`

**Comment by norweeg** [comment]
Three things:  

first of all, did you include the base file?  The add-on files do not stand alone.  They are meant to add to and build upon the base file.  The reverse-proxy service is fully defined in docker-compose.base.yaml.  The subsequent entries for it in the add-ons files add additional configuration to it.  As README.md says, you should be starting your stack by first including the base file and adding the add ons after e.g. `docker-compose -f docker-compose.base.yaml -f add-ons/docker-compose.Grocy.yaml up -d` if you just wanted the base + Grocy.  You can, of course, remove the reverse-proxy and mail-relay from the grocy yaml file and change
```yaml
    expose:
      "80
```
to
```yaml
    ports:
      "80:80"
```
This will make grocy available at http://localhost and it would be the only service that could be run/accessed on port 80 (the default http port) because there won't be a proxy routing requests based on any criteria, it would just be a straight ocnnection

Second, if you're only running this on localhost, it cannot be accessed via HTTPS.  The reverse-proxy may complain that it isn't able to obtain ssl certs for your hostnames because they aren't publically accessible.   It also makes the dynamic-dns service in the base file pointless, since you aren't accessing it from a publicly accessible address  

Finally, if Grocy is all you're looking to run and you only want to run it locally, you can just use [Grocy desktop](https://github.com/grocy/grocy-desktop) directly if you have Windows or using [Wine](https://winehq.org) if you have MacOS or Linux

**Comment by thepenguinthatwants** [comment]
Hi!

Thanks for telling and my bad for not reading the README.md that well.

I took out the reverse proxy and the mail-relay. Thought it seemed to work even with 

    expose:
      "80

Thanks!! I already have own working traefik enviroment.

**Comment by norweeg** [comment]
oh gotcha!  yeah if you have you already have traefik, then leaving the expose clause is appropriate, since your existing traefik is likely already on port 80 and therefore you can't forward that port to anything else.  You didn't include that detail about already having a working Traefik container with docker provider configured.  My templates were written assuming you had absolutely nothing and were just getting started with something.

**Comment by thepenguinthatwants** [comment]
Hi!

Yeah you are right. Sorry I didnt mention the important part of traefik.

Your templates have still helped a lot. Because configuring them feels sometimes quite hard.

Althought I guess the hardest one's are those that dont have web server with them. I still haven no clue how to stiff nginx on the same compose to show certain containers. 

Thank you for the help. Finally having a working grocy.

**Comment by norweeg** [comment]
@thepenguinthatwants any particular server you're thinking of?  I may be able to assist

**Comment by thepenguinthatwants** [comment]
I was thinking of how to use nginx image to get them work with docker images that doesnt have web servers. For example it would be nice to learn how to use it for like privatebin.

There is already a privatebin with nginx  image but the image is in a way that I can't  use volumes to make the files permanent. So it would be nice to learn how to map the images with nginx.

**Comment by norweeg** [comment]
you can make any directory inside the container map to a volume.
